# Generated by Django 5.2.4 on 2025-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_menu_id_alter_menu_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ID',
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
